### ISSUE TITLE
Error parsing hexadecimal operands in pushimm

### ISSUE THREAD

**Issue by BlastFX2** [XlogicX/irasm#3]
In pushimm you strip the 0x from hexadecimal numbers before passing them to disp_to_dec which expects the 0x prefix (without it it treats the number as decimal). 
This leads a potential crash in the zeropad function in case the decoded number fits into a smaller operand than the actual argument. 
For exampe 0x100 is treated as 100=0x64, which would fit into a single byte and then zeropad("100",2) is called and crashes (because we're trying to pad a 3 character long string to a length of 2 and ruby doesn't like "0"*-1). Furthermore, any string containing digits a-f is decoded by disp_to_dec as 0, making the issue much more common. 
I didn't check the rest of the program, but this bug may also be present elsewhere.

**Comment by XlogicX** [comment]
I believe I have fixed this now, thanks for catching that bug. I searched and found 2 other routines that had similar regex capturing (leading to the root cause of this issue) and made sure it didn't have similar issues. Here is an output of a session after the code change:

irasm > push 100
6A64                              push   0x64    

irasm > push 0x100
6800010000                        push   0x100   

66680001                          pushw  0x100    (WORD Sized Alternate)

irasm > push 0xff
6AFF                              push   0xffffffff

**Comment by BlastFX2** [comment]
Oh man, I hate bothering you, but I just tried pasting the output of your debug session—namely push 0xffffffff— back into irasm and it crashes again. 
You only handle operands from 0 to 4294836226 (0xFFFE0002), for anything higher you don't assign an opcode, so when you do m1+ammount, it crashes (because m1 i null). 
Furthermore, push handles the operands as signed integers, so anything starting with 0xffffff80 can be (and by default is) encoded as the 6A push. Irasm is missing that variant.

**Comment by XlogicX** [comment]
hahaha, that sucks, why the hell did I pick that number, I wonder if I had a reason for picking something so arbitrary. No worries bothering me, so long as the bugs are easy enough to fix; turns out it's a little bit of work to write an assembler from scratch. Anyway, I tried just replacing with 4294967296 in hopes that would fix it, which it fixes the crash, but the result it outputs is weird, maybe more on the objdump end though (as in, I'm not the one deciding 6aff is the same thing as push 0xffffffff). So when you feed that disassembled version back in, you get a more literal version of pushing a full 32-bit's if f's. Whatever, what's the point of living...

irasm > push 0xff
6AFF                              push   0xffffffff

My output ( 68FF000000 ) doesn't match that of nasm, something may be wrong here

irasm > push 0xffffffff
68FFFFFFFF                        push   0xffffffff

My output ( 6AFF ) doesn't match that of nasm, something may be wrong here

**Comment by BlastFX2** [comment]
I was thinking something like this: 
```
    elsif disp_to_dec(ammount) > 65535 and disp_to_dec(ammount) < 4294967168 then
        if extracted = /^0x(.+)$/s.match(ammount) then
                ammount = extracted.captures[0]
        end
        ammount = littleend(zeropad(ammount, 8))
        m1 = '68'
    elsif disp_to_dec(ammount) > 4294967167 and disp_to_dec(ammount) < 4294967296 then
        if extracted = /^0x(.+)$/s.match(ammount) then
                ammount = extracted.captures[0]
        end
        ammount1 = littleend(zeropad(ammount[6,2], 2))
        m1 = '6A'
        instruction_alt = objdump(m1 + ammount1)
        printf("%-34s%-15s\n\n", m1 + ammount1, instruction_alt)
        sanity_check(m1 + ammount1, instruction)        #See if this output matches nasms
        ammount2 = littleend(zeropad(ammount, 8))
        m1 = '68'
        instruction_alt = objdump(m1 + ammount2)
        printf("%-34s%-15s\n\n", m1 + ammount2, instruction_alt)
        sanity_check(m1 + ammount2, instruction)        #See if this output matches nasms
        return 1
    end
```
Ouptut:
```
irasm > push 0xffffffff
6AFF                              push   0xffffffff

68FFFFFFFF                        push   0xffffffff

irasm > push 0xffffff80
6A80                              push   0xffffff80

6880FFFFFF                        push   0xffffff80

irasm > push 0xffffff7f
687FFFFFFF                        push   0xffffff7f
```

**Comment by BlastFX2** [comment]
And I just now realized that push 0xff can not be encoded as 6A, because it's a positive integer and 6A can only handle positive integers up to 0x7f. 
I gotta go now, but give me an hour and I'll post complete pushimm code.

**Comment by XlogicX** [comment]
Looking good then. If you're going to write some code, might as well do a pull request right? get some credit for it, aka officially contribute.

**Comment by BlastFX2** [comment]
Nah, I have no idea how this whole git thing works and I don't care about getting rep on this handle anyway. 
Here's the code: 
```
def pushimm(instruction)
	#GateKeeper Parse
	if extracted = /^push\s((\d{1,10})|(0x[a-f0-9]{1,8}))$/i.match(instruction) then
		ammount_unsigned = disp_to_dec(extracted.captures[0])
		if ammount_unsigned < 0 or 0xffffffff < ammount_unsigned then # shouldn't be negative, but decimal number could be too large
			return false
		end
		if ammount_unsigned < 0x80000000 then
			ammount_int = ammount_unsigned
		else
			ammount_int = ammount_unsigned - 0x100000000
		end
	else return false end
	
	if -128 <= ammount_int and ammount_int < 128 then
		ammount = littleend(zeropad((ammount_unsigned & 0xff).to_s(16), 2))
		m1 = '6A'
		instruction_alt = objdump(m1 + ammount)
		printf("%-34s%-15s\n\n", m1 + ammount, instruction_alt)	
		sanity_check(m1 + ammount, instruction)	#See if this output matches nasms
	end

	if -32768 <= ammount_int and ammount_int < 32768 then 
		ammount = littleend(zeropad((ammount_unsigned & 0xffff).to_s(16), 4))
		m1 = '6668'
		instruction_alt = objdump(m1 + ammount)
		printf("%-34s%-15s (WORD Sized Alternate)\n\n", m1 + ammount, instruction_alt)
	end

	ammount = littleend(zeropad(ammount_unsigned.to_s(16), 8))
	m1 = '68'
	instruction_alt = objdump(m1 + ammount)
	printf("%-34s%-15s\n\n", m1 + ammount, instruction_alt)	
	# nasm will use the 6A opcode whenever possible, so the sanity check will fail for single byte operands
	if ammount_int < -128 or 128 <= ammount_int then 
		sanity_check(m1 + ammount, instruction)	#See if this output matches nasms
	end
	return 1

end
``` 
I've tried all the edge cases I could come up with, so hopefully there aren't any bugs.

**Comment by XlogicX** [comment]
Fair enough. I tested as well, pretty good improvement, thanks. Code is updated again.
